/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DataMurid;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class DataSiswa extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;

    String DB_URL = "jdbc:postgresql://localhost:5432/PBO4";
    String USER = "postgres";
    String PASS = "300106";

    public void connect() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal : " + e.getMessage());

        }
    }

    public DataSiswa() {
        initComponents();
        connect();
        tampilData();

    }

  private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("nama");
        model.addColumn("absen");
        model.addColumn("wali_kelas");
        model.addColumn("wali_murid");
       

// load data dari DB
        try (
               Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                Statement st = conn.createStatement(); 
                ResultSet rs = st.executeQuery("SELECT * FROM datasiswa ORDER BY absen")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama"),
                    rs.getInt("absen"),
                    rs.getString("wali_kelas"),
                    rs.getString("wali_murid"),
                   
                });
            }

            Tabel.setModel(model); // tampilkan ke JTable
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfabsen = new javax.swing.JTextField();
        tfwalmur = new javax.swing.JTextField();
        tfwalkel = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA SISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 68, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ABSEN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WALI MURID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WALI KELAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 169, -1));

        tfabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfabsenActionPerformed(evt);
            }
        });
        getContentPane().add(tfabsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 169, -1));

        tfwalmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwalmurActionPerformed(evt);
            }
        });
        getContentPane().add(tfwalmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 169, -1));

        tfwalkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwalkelActionPerformed(evt);
            }
        });
        getContentPane().add(tfwalkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 169, -1));

        jButtonInsert.setBackground(new java.awt.Color(255, 255, 153));
        jButtonInsert.setText("Insert");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, -1));

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 153));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 255, 153));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 80, -1));

        jButtonClear.setBackground(new java.awt.Color(255, 255, 153));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, -1));

        Tabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tabel.setGridColor(new java.awt.Color(255, 255, 255));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 440, 230));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataMurid/pngtree-e-commerce-book-knowledge-teacher-education-banner-background-image_186718.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 790, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void tfabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfabsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfabsenActionPerformed

    private void tfwalmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwalmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfwalmurActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
      try {
            String nama = tfnama.getText();
            int absen = Integer.parseInt(tfabsen.getText());
            String wali_kelas = tfwalkel.getText();
            String wali_murid = tfwalmur.getText();

            connect();
            String sql = "INSERT INTO datasiswa (nama, absen, wali_kelas, wali_murid) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setInt(2, absen);
            ps.setString(3, wali_kelas);
             ps.setString(4, wali_murid);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
             bersih();   // Kosongkan textfield
            tampilData();
        } catch (NumberFormatException | SQLException e) {
            System.out.println("Gagal insert: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            String sql = "UPDATE datasiswa SET nama = ?, absen = ?, wali_kelas = ?, wali_murid = ? WHERE absen = ? ";
           connect();
            PreparedStatement pst = conn.prepareStatement(sql);

            // Ambil dari textfield
            pst.setString(1, tfnama.getText());
            pst.setInt(2, Integer.parseInt(tfabsen.getText()));
            pst.setString(3, tfwalkel.getText());
            pst.setString(4, tfwalmur.getText());
            pst.setInt(5, Integer.parseInt(tfabsen.getText()));
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

            // Refresh tabel
            tampilData();

            // Kosongkan textfield
            tfnama.setText("");
            tfabsen.setText("");
            tfwalkel.setText("");
            tfwalmur.setText("");
            

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        int row = Tabel.getSelectedRow();
        tfnama.setText(Tabel.getValueAt(row, 0).toString());
        tfabsen.setText(Tabel.getValueAt(row, 1).toString());
        tfwalkel.setText(Tabel.getValueAt(row, 2).toString());
        tfwalmur.setText(Tabel.getValueAt(row, 3).toString());

    }//GEN-LAST:event_TabelMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
 try {
            String absen = tfabsen.getText();
            String sql = "DELETE FROM datasiswa WHERE absen='" + absen + "'";
            connect();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

            // Refresh tabel
            tampilData();

            // Kosongkan textfield
           tfnama.setText("");
            tfabsen.setText("");
            tfwalkel.setText("");
            tfwalmur.setText("");
           
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void tfwalkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwalkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfwalkelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bersih() {
        tfnama.setText("");
        tfabsen.setText("");
        tfwalkel.setText("");
        tfwalmur.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    DataSiswa form = new DataSiswa();
                    form.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error creating form: " + e.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfabsen;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfwalkel;
    private javax.swing.JTextField tfwalmur;
    // End of variables declaration//GEN-END:variables
}
